version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reminder-mini-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/reminder-app
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - NODE_ENV=production
      - LOG_LEVEL=info
    volumes:
      - logs:/app/logs
    networks:
      - app-network
      - nginx-network

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  nginx-network:
    external: true  # Это позволит контейнерам подключаться к внешней сети

volumes:
  mongodb-data:
    driver: local
  logs:
    driver: local 